imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:       ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    #trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    trusted_proxies: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ MopaBootstrapBundle, DizdaBankManagerSiteBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less: 
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [ DizdaBankManagerCoreBundle, UserBundle, DizdaCloudBackupBundle ]
        directories: ["%kernel.root_dir%/../src"]

#doctrine_mongodb:
#    connections:
#        default:
#            server: mongodb://localhost:27017
#            options:
#                connect: true
#    default_database: creditmanager
#    document_managers:
#        default:
#            auto_mapping: true
            
            
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

#        sonata.admin_doctrine_orm.block.audit:
#            contexts:   [admin]

        sonata.block.service.text:
        sonata.page.block.container:
        sonata.page.block.children_pages:
        sonata.block.service.rss:
        sonata.media.block.media:
        sonata.media.block.gallery:
        sonata.media.block.feature_media:
          
services:
    dizda.bank.core.admin.account:
        class: Dizda\BankManager\CoreBundle\Admin\AccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Account, label: Account }
        arguments: [null, Dizda\BankManager\CoreBundle\Entity\Account, DizdaBankManagerCoreBundle:AccountAdmin]
    dizda.bank.user.admin.user:
            class: Dizda\BankManager\UserBundle\Admin\UserAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: Account, label: User }
            arguments: [null, Dizda\BankManager\UserBundle\Entity\User, UserBundle:UserAdmin]
#    dizda.bank.user.admin.options:
#            class: Dizda\BankManager\UserBundle\Admin\OptionsAdmin
#            tags:
#                - { name: sonata.admin, manager_type: doctrine_mongodb, group: Account, label: Options }
#            arguments: [null, Dizda\BankManager\UserBundle\Document\Options, UserBundle:OptionsAdmin]
        
#    dizda.bank.menu.main:
#        class: Knp\Menu\MenuItem # the service definition requires setting the class
#        factory_service: dizda.bank.menu.builder
#        factory_method: createMainMenu
#        arguments: ["@request"]
#        scope: request # needed as we have the request as a dependency here
#        tags:
#            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Dizda\BankManager\UserBundle\Entity\User

        
sonata_admin:
    title:      Crédit Manager for CréditMutel
    #title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }


#TEMPORARY
#sonata_block:
#   exception:
#      filters:
#        debug_only: sonata.block.exception.filter.debug_only
#      renderers:
#        page: sonata.block.exception.renderer.inline
#      default:
#        filter: debug_only
#        renderer: page
#   default_contexts:
#      filter: debug_only
#      renderer: page
#TEMPORARY


dizda_cloud_backup:
    cloud_storages:
        dropbox:
            user:     %dizda_cloud_dropbox_user%
            password: %dizda_cloud_dropbox_password%
            remote_path: %dizda_cloud_dropbox_remote_path%

    databases:
        mongodb:
            all_databases: false
            database: creditmanager