<?php

namespace Dizda\BankManager\CoreBundle\Document\MongoDB\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;


/**
 * SiteHitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalanceHistoryRepository extends DocumentRepository
{

    public function getMonthTransactions(/*$account, \DateTime $date*/)
    {

        $dateStart = clone $date->modify('first day of this month')->setTime(0,0,0);
        $dateEnd   = $date->modify('last day of this month')->setTime(23,59,59);


        $qb = $this->createQueryBuilder('s')
                   /*->field('account.$id')->equals($account)
                   ->field('date_transaction')->gte($dateStart)
                   ->field('date_transaction')->lte($dateEnd)*/
                   ->sort('date_transaction', 'desc');

        return $qb->getQuery()->execute();

    }





}